### ISSUE TITLE
Support for PocketCast Files

### ISSUE THREAD

**Issue by benjaminyam** [nwithan8/pycketcasts#3] opened 2021-01-19 02:45 UTC
Hello, would appreciate if you could consider adding this feature.

I would love to automate uploading of files to PocketCast account.

![image](https://user-images.githubusercontent.com/9518517/104981283-4ad95d80-5a43-11eb-9399-7746862183ab.png)

**Comment by nwithan8** [comment] 2021-01-19 03:34
Already am.
Going to close this, since it's a duplicate of https://github.com/nwithan8/pycketcasts/issues/2

**Closed by nwithan8** 2021-01-19 03:34 UTC
